### ISSUE TITLE
Unwrapped tokens stuck in contract while bridging to Ethereum

### ISSUE THREAD

**Issue by StorryTV** [Plenty-DeFi/plenty-interface#765]
The frontend says it has succesfully transferred (released) the tokens, but I received nothing.

I transferred USDC.e tokens from Tezos to USDC tokens on Ethereum. (But it's probably an issue for all tokens we bridge)

After locking the tokens on Tezos and waiting for the signing verifications, the transaction on Ethereum failed, so I tried again. And after it failed again I refreshed the page and went to history of bridge transactions, but there it says it was successful.

Please look into it.

And also, is there a way I can get my unreleased USDC tokens?

**Comment by StorryTV** [comment]
Or the locked Tezos USDC.e tokens back on Tezos?

Tezos Tx id:
[https://tzkt.io/oo6CxjDndNs3qbhWqyvqwYQZ83kS1MWEDrj1jbGKBbCirxZGVtx](url)

**Comment by AniketSindhu** [comment]
@StorryTV try cleaning your local storage and retry again from the history page.

**Comment by StorryTV** [comment]
I just cleared all cookies, localstorage, and refreshed the page with cache reload on in Devtools, then I connected the Tezos wallet and Ethereum wallets. But it still says it was successful, without option to try again. It only gives a link to the tzkt explorer with the transaction where the tokens were being locked on Tezos. But the tokens on Ethereum aren't being sent.

What else can I try?

**Comment by StorryTV** [comment]
There should also be (in my opinion) a "cancel" option after the tokens are locked but not yet send to the other chain, if that is possible.

**Comment by AniketSindhu** [comment]
Your Ethereum transaction went out of gas at the end while transferring the token. 

https://etherscan.io/tx/0x6a30f4bf0b397b61b381995d1f17e4e7b3ed2c7e59eaa0927d865afd3fc88687

We are looking at the issue give us some more time. Sorry for the inconvenience.

**Comment by StorryTV** [comment]
Thanks in advance.

**Comment by AniketSindhu** [comment]
Hey @StorryTV, We finalized your transaction successfully (https://etherscan.io/tx/0x4181f959c4feb3b4318344c531979acad9da5e2809f36cd564bb17c64b9836fb). 

Sorry for the delayed response.
